project_id = "btgmvuieishjiybgcmpj"

[functions.analyze-vision]
verify_jwt = false

[functions.generate-signed-url]
verify_jwt = false

[functions.configure-elevenlabs-agent]
verify_jwt = false

[functions.instacart-create-cart]
verify_jwt = false

[functions.check-admin]
verify_jwt = false

[functions.enrich-product]
verify_jwt = false

[functions.identify-product]
verify_jwt = false

[functions.cook-recipe]
verify_jwt = false

[functions.notify-spoilage]
verify_jwt = false
