project_id = "btgmvuieishjiybgcmpj"

[functions.generate-signed-url]
verify_jwt = false

[functions.configure-elevenlabs-agent]
verify_jwt = false

[functions.instacart-create-cart]
verify_jwt = false
