project_id = "btgmvuieishjiybgcmpj"

[functions.interview-ai]
verify_jwt = false

[functions.kaeva-tts]
verify_jwt = false

[functions.generate-signed-url]
verify_jwt = false

[functions.configure-elevenlabs-agent]
verify_jwt = false
